languageCode = "zh-CN"
title = "MingguiLu - Home Page"
baseurl = "http://www.minggui.com"
theme = ""

[params]
  name = "Minggui Lu"
  about = "Welcome to my home page !"
  copyright = "2017"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:luminggui0214@gmail.com"
  title = "E-mail"

[[params.social]]
  medium = "Blog"
  icon = "book"
  link = "http://blog.mingguilu.com"
  title = "Blog"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/MingguiLu"
  title = "Github"